### PR TITLE
Fixed issue with assigning IDs; Closes #49

### LINKED ISSUE #49: assignID() is assigning invalid IDs
IDs are not getting assigned correctly, which breaks the ability to delete bodies among other things.

### PR DESCRIPTION
**Pull request by aaroncameron21**
There was a scope issue where ‘this.idCounter’ was not visible within a
for loop, so it was assigning undefined values to the body’s ID. Fixed
this and added a test to prevent this kind of error in the future.

### CODE REVIEW

File: src/engine.js [hunk 1]
```diff
@@ -71,17 +71,17 @@ Simulator.prototype.reset = function(bodies) {
  */
 
 Simulator.prototype.assignIDs = function() {
-    this.idCounter = 0;
+    var tempID = 0;
     this.bodies.forEach(function(body) { 
-        body.id = this.idCounter;
```
Comment (benjic) [inline src/engine.js]: `this` has a [different meaning](http://javascriptissexy.com/understand-javascripts-this-with-clarity-and-master-it/) in javascript than traditional OO languages.
